version: '3.8'

services:
  nextjs-app:
    image: node:20-alpine
    container_name: gr3-links-container
    working_dir: ./
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3456"
    command: sh -c "npm install && npm migrate && npm run build && pm2-runtime start npm --name 'nextjs-app' -- start"