name: Deploy Next.js App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: release
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js 20.10
        uses: actions/setup-node@v2
        with:
          node-version: 20.10.0

      - name: Install dependencies
        run: npm install

      - name: Build Next.js app
        run: npm run build

      - name: Update target repo
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: 22
          script: |
            cd ${{ secrets.TARGET_PATH}}
            git pull origin main
            [ -e .next ] &&  rm -r .next
      - name: Copy files to VPS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_PASSWORD }}
          source: ".next"
          target: "${{ secrets.TARGET_PATH }}"
      - name: Run docker
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: 22
          script: |
            docker-compose up --force-recreate