name: Deploy Next.js App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: release
    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: 22
          script: |
            cd /var/www/html/personal-links
            git pull origin main
            nvm use 20.10.0
            npm install
            npm run migrate
            npm run build
            pm2 stop personal-links
            pm2 start "npm run start" --name "personal-links" --interpreter=~/.nvm/versions/node/v20.10.0/bin/node